// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBy9VnFC7-U1DAmWeAYLhaUkJFCPOnA3wA',
    appId: '1:286213262143:web:b420ecf240455342a3e18a',
    messagingSenderId: '286213262143',
    projectId: 'homefoodapp-9400e',
    authDomain: 'homefoodapp-9400e.firebaseapp.com',
    storageBucket: 'homefoodapp-9400e.appspot.com',
    measurementId: 'G-HYJE9HH0LL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFCZR2NILAQiFGQL6GlNTSSfxSU6ceofY',
    appId: '1:286213262143:android:094dc5b9109eb59aa3e18a',
    messagingSenderId: '286213262143',
    projectId: 'homefoodapp-9400e',
    storageBucket: 'homefoodapp-9400e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDubQGej7cFRaO5MMnN6v4RDV4ylsdZ6yw',
    appId: '1:286213262143:ios:8270a833562bd1b6a3e18a',
    messagingSenderId: '286213262143',
    projectId: 'homefoodapp-9400e',
    storageBucket: 'homefoodapp-9400e.appspot.com',
    iosBundleId: 'com.example.homeFood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDubQGej7cFRaO5MMnN6v4RDV4ylsdZ6yw',
    appId: '1:286213262143:ios:8270a833562bd1b6a3e18a',
    messagingSenderId: '286213262143',
    projectId: 'homefoodapp-9400e',
    storageBucket: 'homefoodapp-9400e.appspot.com',
    iosBundleId: 'com.example.homeFood',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBy9VnFC7-U1DAmWeAYLhaUkJFCPOnA3wA',
    appId: '1:286213262143:web:6a367994036411a9a3e18a',
    messagingSenderId: '286213262143',
    projectId: 'homefoodapp-9400e',
    authDomain: 'homefoodapp-9400e.firebaseapp.com',
    storageBucket: 'homefoodapp-9400e.appspot.com',
    measurementId: 'G-CXQCHPKV47',
  );
}
